routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Backend\IndexController;
use App\Http\Controllers\Backend\ClassController;
use App\Http\Controllers\Backend\RoleController;
use App\Http\Controllers\Backend\SectionsController;
use App\Http\Controllers\Backend\UserController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Backend\AdminsController;
use App\Http\Controllers\Backend\ClientController;
use App\Http\Controllers\Backend\DomainController;
use App\Http\Controllers\Backend\HostingCategoryController;
use App\Http\Controllers\Backend\HostingController;
use App\Http\Controllers\Backend\SystemSettingsController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});



Auth::routes();
// login routes
Route::get('admin/login', [LoginController::class, 'showLoginForm'])->name('admin.login');
Route::post('admin/login/submit', [LoginController::class, 'login'])->name('admin.login.submit');


// admin routes
Route::middleware(['auth:admin'])->group(function () {
    Route::group(['prefix' => 'admin'], function () {
        Route::get('/', [IndexController::class, 'index'])->name('dashboard');
        Route::resource('roles', RoleController::class);
        Route::resource('users', UserController::class);
        Route::resource('admin', AdminsController::class);
        Route::resource('class', ClassController::class);
        Route::resource('client', ClientController::class);
        Route::resource('domain', DomainController::class);
        Route::resource('section', SectionsController::class);
        Route::resource('hosting', HostingController::class);
        Route::post('/hosting/{id}', [HostingController::class, 'destroy'])->name('myhosting.destroy');
        Route::resource('hostingcategory', HostingCategoryController::class);
        Route::resource('systemsetting', SystemSettingsController::class);

        Route::get('/view-invoice/{id}', [HostingController::class, 'ViewInvoice'])->name('view.invoice');

        // logout routes
        Route::post('/logout/submit', [LoginController::class, 'logout'])->name('admin.logout.submit');
        Route::post('/payment', [HostingController::class, 'MakePayment'])->name('make-payment');
        Route::post('/payment/{id}', [HostingController::class, 'UpdatePayment'])->name('update-payment');
        Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

        //Forget Password Routes
        Route::get('/password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('admin.password.reset');
        Route::post('/passwordreset/submit', [LoginController::class, 'reset'])->name('admin.password.update');
    });
});

app/Http/Controllers/Backend/AdminsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Admin;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Role;

class AdminsController extends Controller
{
    public $user;
    public function __construct()
    {
        $this->middleware(function ($request, $next) {
            $this->user = Auth::guard('admin')->user();
            return $next($request);
        });
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (is_null($this->user) || !$this->user->can('admin.view')) {
            abort(403, 'Sorry You are Unauthorized Access To View any Admin');
        }
        $admin = Admin::all();
        //dd($admin);
        return view('Backend.admin.view', compact('admin'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (is_null($this->user) || !$this->user->can('admin.create')) {
            abort(403, 'Sorry You are Unauthorized Access To Create any Admin');
        }
        $roles = Role::all();
        return view('Backend.admin.add', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (is_null($this->user) || !$this->user->can('admin.create')) {
            abort(403, 'Sorry You are Unauthorized Access To Create any Admin');
        }
        //validate data
        $request->validate([
            'name' => 'required|max:50',
            'email' => 'required|max:100|email|unique:admin',
            'username' => 'required|max:100|unique:admin',
            'password' => 'required|max:100|min:8|confirmed',
        ], [
            'name.required' => 'please give a admin name',
            'name.email' => 'please give admin email'
        ]);
        // create new admin
        $admin = new Admin();
        $admin->name = $request->name;
        $admin->email = $request->email;
        $admin->username = $request->username;
        $admin->password = Hash::make($request->password);
        $status = $admin->save();

        //asign roles to this admin
        if ($request->roles) {
            $admin->assignRole($request->roles);
        }

        if ($status) {
            return redirect()->route('admin.index')->with('success', 'admin Created Successfully');
        } else {
            return redirect()->route('admin.index')->with('error', 'Error in Creating admin');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (is_null($this->user) || !$this->user->can('admin.edit')) {
            abort(403, 'Sorry You are Unauthorized Access To Edit any Admin');
        }
        $admin = Admin::find($id);
        $roles = Role::all();
        return view('Backend.admin.edit', compact('admin', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (is_null($this->user) || !$this->user->can('admin.edit')) {
            abort(403, 'Sorry You are Unauthorized Access To Edit any Admin');
        }
        //validate data
        $request->validate([
            'name' => 'required|max:50',
            'email' => 'required|max:100|email|unique:admin,email,' . $id,
            // 'username'=>'required|max:100|unique:admin',
            'password' => 'nullable|min:8|confirmed',
        ], [
            'name.required' => 'please give a admin name',
            'name.email' => 'please give admin email'
        ]);
        // create new admin
        $admin = Admin::find($id);
        $admin->name = $request->name;
        $admin->email = $request->email;
        $admin->username = $request->username;
        if ($request->password) {
            $admin->password = Hash::make($request->password);
        }
        $status = $admin->save();
        $admin->roles()->detach();
        //asign roles to this admin
        if ($request->roles) {
            $admin->assignRole($request->roles);
        }

        if ($status) {
            return redirect()->route('admin.index')->with('success', 'admin Updated Successfully');
        } else {
            return redirect()->route('admin.index')->with('error', 'Error in Updated admin');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (is_null($this->user) || !$this->user->can('admin.delete')) {
            abort(403, 'Sorry You are Unauthorized Access To Delete any Admin');
        }
        $admin = Admin::find($id);
        if (!is_null($admin)) {
            $status = $admin->delete();
            if ($status) {
                return redirect()->route('admin.index')->with('success', 'admin Deleted Successfully');
            } else {
                return redirect()->route('admin.index')->with('error', 'Error in Deleting admin');
            }
        }
    }
    public function logout()
    {
        Auth::logout();
        return redirect()->route('login');
    }
}

app/Http/Controllers/Backend/ClassController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\ClassesRequest;
use App\Models\Classes;
use App\Repositories\Classes\ClassRepository;
use App\Repositories\Sections\SectionRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ClassController extends Controller
{
    public $classRepository;
    public $sectionRepository;
    public $user;
    public function __construct(ClassRepository $classRepository, SectionRepository $sectionRepository)
    {
        $this->classRepository = $classRepository;
        $this->sectionRepository = $sectionRepository;

        $this->middleware(function($request,$next){
            $this->user=Auth::guard('admin')->user();
            return $next($request);
        });

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(is_null($this->user)||!$this->user->can('class.view') ){
        abort(403,'Sorry You are Unauthorized Access To View any Class');
    }
        $classes = $this->classRepository->getAllClass();
        return view('Backend.class.view', compact('classes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(is_null($this->user)||!$this->user->can('class.create') ){
            abort(403,'Sorry You are Unauthorized Access To Create any Class');
        }
        $sections = $this->sectionRepository->getAllSection();
        //dd($section);
        return view('Backend.class.add', compact('sections'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ClassesRequest $request)
    {
        if(is_null($this->user)||!$this->user->can('class.create') ){
            abort(403,'Sorry You are Unauthorized Access To Create any Class');
        }
        $class = $this->classRepository->addClass($request->all());
        if ($class) {
            return redirect()->route('class.index')->with('success', 'Class Added Successfully');
        } else {
            return redirect()->route('class.create')->with('error', 'Error in Adding Class');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $classId
     * @return \Illuminate\Http\Response
     */
    public function edit($classId)
    {
        if(is_null($this->user)||!$this->user->can('class.edit') ){
            abort(403,'Sorry You are Unauthorized Access To Edit any Class');
        }
        $sections = $this->sectionRepository->getAllSection();
        $class = $this->classRepository->getSingleClass($classId);
        return view('Backend.class.edit', compact('class', 'sections'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $classId
     * @return \Illuminate\Http\Response
     */
    public function update(ClassesRequest $request, $classId)
    {

        if(is_null($this->user)||!$this->user->can('class.edit') ){
            abort(403,'Sorry You are Unauthorized Access To Edit any Class');
        }
        $class = $this->classRepository->updateClass($request->all(), $classId);
        if ($class) {
            return redirect()->route('class.index')->with('success', 'Class Updated Successfully');;
        } else {
            return redirect()->route('class.index')->with('error', 'Error in Updating Class');;
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($classId)
    {

        if(is_null($this->user)||!$this->user->can('class.edit') ){
            abort(403,'Sorry You are Unauthorized Access To Delete any Class');
        }
        $class = $this->classRepository->deleteClass($classId);
        if ($class) {
            return redirect()->route('class.index')->with('success', 'Class Deleted Successfully');
        } else {
            return redirect()->route('class.index')->with('error', 'Error in Deleting Class');
        }
    }
}

app/Http/Controllers/Backend/IndexController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Client;
use App\Models\Domain;
use App\Models\Hosting;
use App\Models\HostingCategory;
use Illuminate\Support\Facades\Auth;

class IndexController extends Controller
{
    public $user;
    public function __construct()
    {
        $this->middleware(function ($request, $next) {
            $this->user = Auth::guard('admin')->user();
            return $next($request);
        });
    }
    public function index()
    {
        $client = Client::count();
        $domain = Domain::count();
        $expiration_date = now()->addDays(15);
        $expiring_domain = Domain::where('expiry_date', '<=', $expiration_date)->limit(6)->get();
        // dd($expiring_domain);
        $hosting = Hosting::count();

        $expiring_hosting = Hosting::where('expiry_date', '<=', $expiration_date)->with('domain')->with('client')->with('hosting_cat')->limit(6)->get();
        //dd($expiring_hosting);

        $hosting_category = HostingCategory::count();
        if (is_null($this->user) || !$this->user->can('dashboard.view')) {
            abort(403, 'Sorry You are Unauthorized Access To View Dashboard');
        }
        return view('Backend.dashboard.index', compact('client', 'domain', 'hosting', 'hosting_category', 'expiring_hosting','expiring_domain'));
    }
}

app/Http/Controllers/Backend/PaymentController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class PaymentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/Backend/role/add.blade.php
@extends('Backend.dashboard.main')

@section('content')
<div class="content container-fluid">

    <div class="page-header">
        <div class="row align-items-center">
            <div class="col">
                <h3 class="page-title">Add Role</h3>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('roles.index') }}">Roles</a></li>
                    <li class="breadcrumb-item active">Add Role</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">

                    <form method="POST" action="{{ route('roles.store') }}">
                        @csrf
                        <div class="row">

                            <div class="col-12 col-sm-6">
                                <div class="form-group local-forms">
                                    <label>Role <span class="login-danger">*</span></label>
                                    <input type="text" class="form-control @error('name')is-invalid @enderror" name="name" value="{{ old('name') }}" placeholder="Enter a New Role">
                                    @error('name')
                                    <p style="color: indianred;margin-top: 5px">{{ $message }}</p>
                                    @enderror
                                </div>

                            </div>
                            <h6>permissions</h6>
                             <div class="col-md-10">

                                <div class="form-group" style="margin-bottom:0.2rem">
                                    <input type="checkbox"   value="1" id="checkPermissionAll" style="cursor: pointer">
                                    <label for="checkPermissionAll" style="cursor:pointer" class="mb-0">Give All Permissions</label>
                                </div>
                                <hr>
                                @php $i=1 @endphp
                                @foreach ($permission_groups as $group)

                                <div class="row">
                                    <div class="col-3">
                                        <div class="form-group" style="margin-bottom:0.2rem">
                                            <input type="checkbox"  value="{{ $group->name }}"onclick="checkPermissionByGroup('role-{{ $i }}-management-checkbox', this)" id="{{ $i }}Management" style="cursor: pointer">
                                            <label for="{{ $i }}Management" style="cursor:pointer" class="mb-0">{{ $group->name }}   </label>
                                        </div>
                                    </div>
                                    <div class="col-9 role-{{ $i }}-management-checkbox">
                                        @php
                                            $permissions=App\Models\User::getpermissionsByGroupName($group->name);
                                            $j=1;
                                        @endphp
                                        @if ($permissions)
                                        @foreach ($permissions as $permission )
                                        <div class="form-group" style="margin-bottom:0.2rem">
                                            <input type="checkbox" name="permission[]" value="{{ $permission->name }}" id="permission-checkbox{{ $permission->id }}" style="cursor: pointer">
                                            <label for="permission-checkbox{{ $permission->id }}" style="cursor:pointer" class="mb-0">{{ $permission->name }}   </label>
                                        </div>
                                        @php  $j++; @endphp
                                        @endforeach


                                        @endif
                                    </div>
                                </div>
                                <hr>
                                @php  $i++; @endphp
                                @endforeach




                                </div>
                            <div class="col-12">
                                <div class="student-submit">
                                    <button type="submit" class="btn btn-primary">Save Role</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
@include('Backend.dashboard.scripts.permission-checkbox')
@endsection

resources/views/Backend/role/edit.blade.php
@extends('Backend.dashboard.main')

@section('content')
<div class="content container-fluid">

    <div class="page-header">
        <div class="row align-items-center">
            <div class="col">
                <h3 class="page-title">Edit Role - {{ $role->name }}</h3>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('roles.index') }}">Roles</a></li>
                    <li class="breadcrumb-item active">Edit Role</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">

                    <form method="POST" action="{{ route('roles.update',$role->id) }}">
                        @csrf
                        @method('PUT')
                        <div class="row">

                            <div class="col-12 col-sm-6">
                                <div class="form-group local-forms">
                                    <label>Role <span class="login-danger">*</span></label>
                                    <input type="text" class="form-control @error('name')is-invalid @enderror" name="name" value="{{ $role->name }}"  placeholder="Enter a New Role">
                                    @error('name')
                                    <p style="color: indianred;margin-top: 5px">{{ $message }}</p>
                                    @enderror
                                </div>

                            </div>
                            <h6>permissions</h6>
                             <div class="col-md-10">

                                <div class="form-group" style="margin-bottom:0.2rem">
                                    <input type="checkbox" value="1" id="checkPermissionAll" {{ App\Models\User::roleHasPermissions($role, $all_permission_in_database) ? 'checked' : '' }} style="cursor: pointer">
                                    <label for="checkPermissionAll" style="cursor:pointer" class="mb-0">Give All Permissions</label>
                                </div>
                                <hr>
                                @php $i=1 @endphp
                                @foreach ($permission_groups as $group)

                                @php
                                $permissions=App\Models\User::getpermissionsByGroupName($group->name);
                                $j=1;
                            @endphp

                                <div class="row">
                                    <div class="col-3">
                                        <div class="form-group" style="margin-bottom:0.2rem">
                                            <input type="checkbox"  value="{{ $group->name }}"onclick="checkPermissionByGroup('role-{{ $i }}-management-checkbox', this)" id="{{ $i }}Management" style="cursor: pointer" {{ App\models\User::roleHasPermissions($role,$permissions) ?'checked':'' }}>
                                            <label for="{{ $i }}Management" style="cursor:pointer" class="mb-0">{{ $group->name }}   </label>
                                        </div>
                                    </div>
                                    <div class="col-9 role-{{ $i }}-management-checkbox">
                                        @if ($permissions)
                                        @foreach ($permissions as $permission)
                                        <div class="form-group" style="margin-bottom:0.2rem">
                                            <input type="checkbox" onclick="checkSinglePermission('role-{{ $i }}-management-checkbox', '{{ $i }}Management', {{ count($permissions) }})" name="permission[]" value="{{ $permission->name }}" {{ $role->hasPermissionTo($permission->name)? 'checked':''  }} id="permission-checkbox{{ $permission->id }}" style="cursor: pointer">
                                            <label for="permission-checkbox{{ $permission->id }}" style="cursor:pointer" class="mb-0">{{ $permission->name }}   </label>
                                        </div>
                                        @php  $j++; @endphp
                                        @endforeach


                                        @endif
                                    </div>
                                </div>
                                <hr>
                                @php  $i++; @endphp
                                @endforeach




                                </div>
                            <div class="col-12">
                                <div class="student-submit">
                                    <button type="submit" class="btn btn-primary">Update Role</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
@include('Backend.dashboard.scripts.permission-checkbox')
@endsection

resources/views/Backend/role/view.blade.php
@extends('Backend.dashboard.main')
@section('content')
    <div class="content container-fluid">

        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="page-title">Roles</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li>
                        <li class="breadcrumb-item active">Roles</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="card card-table">
                    <div class="card-body">

                        <div class="page-header">
                            <div class="row align-items-center">
                                <div class="col">
                                    <h3 class="page-title">Available Roles</h3>
                                </div>
                                <div class="col-auto text-end float-end ms-auto download-grp">

                                    <a href="{{ route('roles.create') }}" title="add new role" class="btn btn-primary"><i
                                            class="fas fa-plus"></i>&nbsp;add new role</a>
                                </div>
                            </div>
                        </div>

                        <table
                            class="table border-0 star-student table-hover table-center mb-0 datatable table-striped">
                            <thead class="student-thread">
                            <tr>
                                <th>
                                    <div class="form-check check-tables">
                                        <input class="form-check-input" type="checkbox" value="something">
                                    </div>
                                </th>
                                <th width="5%">ID</th>

                                <th width="10%">Role</th>
                                <th>Permissions</th>


{{--                                <th>No of Students</th>--}}
                                <th class="text-end">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @if($all_roles_in_database->isNotEmpty())
                                @foreach($all_roles_in_database as $key=>$value)
                                    <tr>
                                        <td>
                                            <div class="form-check check-tables">
                                                <input class="form-check-input" type="checkbox" value="something">
                                            </div>
                                        </td>
                                        <td>{{ $key+1 }}</td>

                                        <td>{{ $value->name }}</td>
                                        <td>

                                            @foreach ($value->permissions as $perm)
                                            <span class="badge badge-success mr-1">
                                                {{ $perm->name }}
                                            </span>

                                            @endforeach
                                        </td>

{{--                                        <td>180</td>--}}
                                        <td class="text-end">
                                            <div class="actions">
                                                <a href="{{ route('roles.edit',$value->id) }}" class="btn btn-sm bg-success-light me-2">
                                                    <i class="feather-edit"></i>
                                                </a>
                                                <form action="{{ route('roles.destroy',$value->id) }}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-sm bg-danger-light">
                                                    <i class="feather-trash"></i>
                                                </button>
                                                </form>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection